name: Space News Scraper - Daily Run

on:
  schedule:
    # Run every day at 8:00 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write  # Allow the action to push to the repository

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Scrapy spiders
      env:
        ENVIRONMENT: production
      run: python run_scrapy.py all --limit 20
    
    - name: Commit and push scraped articles
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/articles/
        if git diff --staged --quiet; then
          echo "No new articles to commit"
        else
          git commit -m "Daily scrape: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        fi
