name: Web Scraper - Weekly Run

on:
  schedule:
    # Run every Monday at 9:00 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run scraper
      env:
        ENVIRONMENT: production
      run: python main.py
    
    - name: Commit and push scraped articles
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/articles/
        git commit -m "Weekly scrape: $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
        git push
